#!/bin/sh

sudo apt install git build-essential libglib2.0-dev \
    libgtk-3-dev gettext automake libx11-dev \
    libxft-dev libxpm-dev libxt-dev libxext-dev x11proto-dev \
    libxinerama-dev libxtst-dev libxkbcommon-dev libgsl-dev \
    appmenu-gtk3-module
